---
name: Checks # name of file

on: [push] # run this everytime we push to github

jobs:
  test-lint:  # id for job we run
    name: Test and Lint   # name of test inside this job
    runs-on: ubuntu-20.04 # what we use to run for the job (should have docker compose already installed)
    steps:  # different things that run for the job\
      - name: Login to Docker Hub # name of the step that will show on github
        uses: docker/login-action@v1  # a action that exists in docker repository and the version for it
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2 # checks our code out in our code on github
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" # run unit test
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"